### ISSUE TITLE
Python error: No module named requests

### ISSUE THREAD

**Issue by JosXa** [khadiwala/wundervim#1]
Hi,
I tried installing python-requests from the "extra"-repository on my arch linux but am getting the following error when starting my vim with wundervim imported:

```
Error detected while processing function provider#python#Call:
line   18:
ImportError('No module named requests',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/lib/python2.7/site-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/lib/python2.7/site-packages/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 77, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 4, in <module>
ImportError: No module named requests
```

Somehow it does not seem to recognize the requests package that I installed.

Specs:
NeoVim compiled with Python 2.7.11
ArchLinux
Installed python-requests from repo: extra/python-requests 2.9.1-1 - Python HTTP for Humans
imported wundervim by `NeoBundle 'khadiwala/wundervim'`

I would appreciate any hint of why it could not work. Thanks in advance :)

**Comment by khadiwala** [comment]
I think you may want the python2 requests package instead:
https://www.archlinux.org/packages/extra/any/python2-requests/

Let me know if that helps.

**Comment by JosXa** [comment]
Great, thanks! That fixed it.
